apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://forgejo:password@postgres-db.default.svc.cluster.local:5432/forgejo?sslmode=disable"
