serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: prometheus
  interval: 30s

extendedMetrics: true

config:
  datasource:
    host: "postgres-db.default.svc.cluster.local"
    port: "5432"
    user: "forgejo"
    password: "password"
    database: "forgejo"
    sslmode: "disable"
