apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pvc
  labels:
    type: local
    app: postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "{{ .Values.postgres.storagePath }}"
