apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | b64dec }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64dec }}
