apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    app: postgres-db
spec:
  ports:
    - name: "5432"
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
    app: postgres-db
