apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibGlsbW9vbmx5IiwicGFzc3dvcmQiOiJnaHBfTjg2OXVFTTlXeFhvY2dadUV1THM3N09RQ213R0ZHNDdEb0R4IiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiYXV0aCI6ImJHbHNiVzl2Ym14NU9tZG9jRjlPT0RZNWRVVk5PVmQ0V0c5aloxcDFSWFZNY3pjM1QxRkRiWGRIUmtjME4wUnZSSGc9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
