apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-ss
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: "postgres-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - secretRef:
            name: postgres-db-secrets
        volumeMounts:
        - name: postgres-db-volume
          mountPath: /var/lib/postgresql/data
        - name: dump-volume
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: postgres-db-volume
        persistentVolumeClaim:
          claimName: postgres-db-pvc
      - name: dump-volume
        secret:
          secretName: forgejo-dump
