apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pvc
  labels:
    type: local
    app: postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
