apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
  labels:
    app: postgres-db
spec:
  storageClassName: manual 
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
