apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.forgejo.service.name }}
spec:
  selector:
    app: forgejo-app
  ports:
    - name: "http"
      port: {{ .Values.forgejo.service.port }}
      targetPort: {{ .Values.forgejo.service.port }}
