apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forgejo-blackbox
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /probe
      scheme: http
      params:
        module: [http_2xx]
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_ip]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  jobLabel: forgejo-blackbox
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: forgejo-app
